// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrAgent.Data;

namespace Materials_storage_subsystem.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230320104935_fifth")]
    partial class fifth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StrAgent.Models.Dogovor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Described")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDAg")
                        .HasColumnType("int");

                    b.Property<int>("IDKl")
                        .HasColumnType("int");

                    b.Property<int>("IDTr")
                        .HasColumnType("int");

                    b.Property<int?>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TarifId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("KlientId");

                    b.HasIndex("TarifId");

                    b.ToTable("Dogovors");
                });

            modelBuilder.Entity("StrAgent.Models.StrSl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Described")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DogovorId")
                        .HasColumnType("int");

                    b.Property<int>("IDAg")
                        .HasColumnType("int");

                    b.Property<int>("IDDogv")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("DogovorId");

                    b.ToTable("StrSls");
                });

            modelBuilder.Entity("StrAgent.Models.Tarif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Object")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Tarifs");
                });

            modelBuilder.Entity("StrAgent.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("StrAgent.Models.Roles.Admin", b =>
                {
                    b.HasBaseType("StrAgent.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("StrAgent.Models.Roles.Agent", b =>
                {
                    b.HasBaseType("StrAgent.Models.User");

                    b.HasDiscriminator().HasValue("Agent");
                });

            modelBuilder.Entity("StrAgent.Models.Roles.Policyholder", b =>
                {
                    b.HasBaseType("StrAgent.Models.User");

                    b.HasDiscriminator().HasValue("Policyholder");
                });

            modelBuilder.Entity("StrAgent.Models.Dogovor", b =>
                {
                    b.HasOne("StrAgent.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("StrAgent.Models.User", "Klient")
                        .WithMany()
                        .HasForeignKey("KlientId");

                    b.HasOne("StrAgent.Models.Tarif", "Tarif")
                        .WithMany("Dogovor")
                        .HasForeignKey("TarifId");

                    b.Navigation("Agent");

                    b.Navigation("Klient");

                    b.Navigation("Tarif");
                });

            modelBuilder.Entity("StrAgent.Models.StrSl", b =>
                {
                    b.HasOne("StrAgent.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("StrAgent.Models.Dogovor", "Dogovor")
                        .WithMany("StrSl")
                        .HasForeignKey("DogovorId");

                    b.Navigation("Agent");

                    b.Navigation("Dogovor");
                });

            modelBuilder.Entity("StrAgent.Models.Dogovor", b =>
                {
                    b.Navigation("StrSl");
                });

            modelBuilder.Entity("StrAgent.Models.Tarif", b =>
                {
                    b.Navigation("Dogovor");
                });
#pragma warning restore 612, 618
        }
    }
}
